### PR TITLE
typo removed

### PR DESCRIPTION
**Pull request by Pfiffikus**
What about to use the original version in/for ../cfg.d?

### CODE REVIEW

**Review by drn05r — APPROVED** [review]
Happy with this typo fix.

**Review by drn05r — COMMENTED** [review]
I think the reference to cfg/cfg.d/ is unclear which directory is meant.  Does it mean EPRINTS_PATH/cfg/cfg.d/ or EPRINTS_PATH/archives/ARCHIVE_NAME/cfg/cfg.d/?  I will investigate before applying this patch.  I assume by the reference to 'not over-written when you upgrade' this means the latter.

**Comment by Pfiffikus** [comment]
> I assume by the reference to 'not over-written when you upgrade' this means the latter.

e.g. `EPRINTS_PATH/site_lib/cfg.d/repository.pl` does _not_ work, but `EPRINTS_PATH/cfg/cfg.d/repository.pl` _does_ ...

> What about to use the original version in/for ../cfg.d?

intends to say: `../cfg.d` has no alike `README` ... but should?!

**Comment by drn05r** [comment]
OK.  I will take a proper look at this because there are far too many caveats that need to be explained.  I know some files are automatically copied to the archive when you create a new archive but those should be from defaultcfg or defaultcfg_zero.  I have never properly understood what purpose syscfg.d provides over other cfg.d type directories.  So I think I need to know this before I start updating advice so it actually reflects what happens.

**Comment by drn05r** [comment]
I have checked 'load_system_config' method in perl_lib/EPrints/Config.pm and the README is correct as I understand.  

As I understand it various ways you might upgrade EPrints might lead to the files in lib/syscfg.d/ being overwritten or at least have issues like .rpmnew files being created if you upgrade using YUM.  However, as there is no cfg/syscfg.d/ by default this cannot be overwitten by an upgrade so if you want to make any changes to system level settings like permissions to use for newly created files or directories then you want to copy core.pl into cfg/cfg.d/

**Pull request closed without merging**
