### PR TITLE
Allow custom list of fields for meta tags in summary pages

### PR DESCRIPTION
**Pull request by jesusbagpuss**
Relating to #91 and discussion around control of meta tags.

### CODE REVIEW

**Comment by jesusbagpuss** [comment]
Just to mention - the alteration to eprint_render.pl could be placed in a new file, or a defaultcfg/cfg.d file - I wasn't sure of the best place to put it!

**Review by drn05r — APPROVED** [review]
This looks good to me happy to merge and then test as there is very little that could break.

**Comment by jesusbagpuss** [comment]
I've been mulling this over a bit more.
Depending on what happens with the xml revision stuff, it might be worth having a specific 'exclude' list alongside (or as well as) the suggested custom list.

If this is always defined, bazaar packages can push any of their fields onto the array of excluded fields.

With the above implementation, the first package that wanted to exclude some of it's fields (but wasn't setting export_as_xml=>0) would need to define _all_ the to-be-exported fields.

A slightly wider 'internal' vs 'external' flag for fields might be best longer term - so any export plugin called by a 'staff' user can include internal fields, but other than that they are excluded.

**Comment by drn05r** [comment]
Yes, I think although hvaing both options may be a bit confusing as long as it is well documented I think users will be able to get their heads around it.

Am I correct to assume that the code you have provided here will completely ignore the export_as_xml attribute?

**Comment by jesusbagpuss** [comment]
In the Export::Simple plugin, there is already a test for export_as_xml.
If a field is added to the new list, it won't override that test - so you can't include something that is explicitly set to not export.

**Comment by drn05r** [comment]
Quite right.  I should not try to evaluate code when I am a rush to get out the door.  I forgot that the test determines whether to skip the current field rather than whether to include it.  Combined with an 'unless' it was enough to throw me on this brief inspection.

**Pull request merged**
