### PR TITLE
Possible fix for #395

### PR DESCRIPTION
**Pull request by jesusbagpuss**

### CODE REVIEW

**Review by drn05r — COMMENTED** [review]
I assume by passing `%opts` to the configuration defined function there is no longer nay need to perform: 
```if (!$searchexp->is_blank()) { $list = $list->intersect( $searchexp->perform_search ); }```
If you agree that is the case then I am happy to approve.

**Comment by jesusbagpuss** [comment]
Yes, I agree.

I've taken that out - but on a second review, there was an unused searchexp too - which I've just taken out.

**Comment by jesusbagpuss** [comment]
I guess if someone has previously used the config method, their code and the new stuff won't play nicely.

As neither of us were really aware of this as a config option before, I guess it's unlikely, although still possible - so release notes should mention it. I'm happy to write something to flag this change.

**Review by drn05r — APPROVED** [review]
Looks good to me.

**Pull request merged**
