### PR TITLE
Update reset_password

### PR DESCRIPTION
**Pull request by gobfrey**
Rate limit reset password to prevent an attacker using the repository to script the sending of multiple emails to a repository user.

### CODE REVIEW

**Comment by drn05r** [comment]
@gobfrey It would be nice if the limit (i.e. 24 hours) could be configurable.  Although, as it is a cgi script it is not too much hassle for someone to copy locally and edit as they wish.  Its just they would not get any subsequent changes to reset_password and I could quite believe these future changes being security fixes/enhancements.

**Comment by gobfrey** [comment]
In theory, yes.  In practice, are you sure it's necessary?  Under what use-case would this need to be configured?

**Comment by gobfrey** [comment]
Also, once accepted into master, it closes a security issue.  If you'd like it to also be configurable, I'm very happy for you to further improve it.

**Comment by drn05r** [comment]
Fair enough better to have the security now and worry about configurability at a later date if necessary.

**Pull request merged**
