### PR TITLE
Class attribute additions - view details workflow tab 

### PR DESCRIPTION
**Pull request by fatchild**
- Addition of details table class
- Addition of details table title class
- Addition of tab link class

### CODE REVIEW

**Review by drn05r — COMMENTED** [review]
This is a bit of a mess commits wise.  Two have already been merged and two are just merges back the other way.  I think the only effective change is adding the class `ep_view_details_table` to the table on `EPrint::Workflow::Details` screen plugin.

**Comment by drn05r** [comment]
I think the best plan is to close this pull request and just make the change identified in the review as its own commit directly to master.

**Comment by drn05r** [comment]
Actually there a re few other changes from https://github.com/eprints/eprints3.4/pull/251/commits/8a0c482ebe2c25c6b4e5b8ff378c3b1a72bb9dc7 that I would need to include along with the change mentioned in my review.

**Comment by fatchild** [comment]
Opening new commit in this ones place

**Pull request closed without merging**
